pipelines:
  exchange-rates-api:
    access_key: $EXCHANGE_RATES_API_ACCESS_KEY

profiles:
  dirname: "profiles/"

logger:
  console:
    level: silly
  error:
    filename: "logs/error.log"
  user:
    filename: "logs/user.log"
